FROM node:22-alpine AS builder

WORKDIR /app

COPY backend/package.json .
COPY backend/package-lock.json .

RUN npm ci --prod
COPY backend/ .

WORKDIR /client

COPY client/package.json .
COPY client/package-lock.json .

RUN npm ci --prod
COPY client/ .
RUN npm run build

WORKDIR /app
RUN cp -r /client/dist/* src/static/

CMD ["npm" "run" "dev]
